### PR TITLE
make protoc architecture section more readable

### PR DESCRIPTION
**Pull request by hedenface**
I was interested in using the project, and attempting to read the Makefile and came across this section. To be very honest, I'm not quite sure what the backwards compatibility of this change is - but in any modern make binary this works perfectly, and is clearly more readable than the predecessor.

### CODE REVIEW

**Comment by hedenface** [comment]
I'm not sure those failures have anything to do with what I've pushed here - but it looks like they don't.

**Comment by raphael** [comment]
Thank you for the PR, nice little cleanup! These errors do seem unrelated - I'll take a look.

**Comment by raphael** [comment]
The [build is fixed](https://github.com/goadesign/goa/pull/2724) in the `v3` head, could you rebase and update the PR? thank you!

**Comment by hedenface** [comment]
I've never done this through the UI across forks, but I think I got it done :)

**Comment by hedenface** [comment]
Hooray. Thanks for help

**Comment by raphael** [comment]
Thank you!

**Pull request merged**
