### PR TITLE
WIP: Add constructor method to generators

### PR DESCRIPTION
**Pull request by ottogiron**
fixes https://github.com/goadesign/goa/issues/986

Hi @raphael, 

I'm creating an early PR with a proposal of the possible API for constructors methods for generators. It is based on a short article by Rob Pike about functional options API's 

https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html.

Also explained by Dave Cheney here: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis 

### Available options (settable as a functional option)
gen_app/options.go
```
package genapp

//Option a generator option definition
type Option func(*Generator)

//API The API definition
func API(API *design.APIDefinition) Option {
	return func(g *Generator) {
		g.API = API
	}
}

//From here not showing the implementation.

//OutDir Path to output directory
func OutDir(outDir string) Option 

...
//Target Name of generated package
func Target(target string) Option 

...
//NoTest Whether to skip test generation
func NoTest(noTest bool) Option 
...
```

### Definition of constructor
gen_app/generator.go
```

//NewGenerator returns an initialized instance of an Application Generator
func NewGenerator(options ...Option) *Generator {
	g := &Generator{}

	g.validator = codegen.NewValidator()

        //applying options
	for _, option := range options {
		option(g)
	}

	return g
}
```

### Configuring and running a generator
eg. gen/main.go
```
func main() {
	codegen.ParseDSL()
	codegen.Run(
		genapp.NewGenerator(
				genapp.API(design.Design),
				genapp.OutDir("app"),
                                 // other options
			),
            ...)
}
```

I have used this pattern for libraries in my current company, it is flexible and it has worked well. 

Other options for implementing this might be an static set of parameters (maybe the number of options won't change), or an options struct. 

Let me know what do you think, I would be glad to implement the solution based on what fits the best for the current codebase.

Thanks,

Otto.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the pointer! it seems like the functional option pattern could work well here. One  question I'm wondering is whether each `gen_xxx` package should define its own option function type or whether it would be better to declare it once (e.g. in the `codegen` package). The package that defines the type could also define the common options to all the generators (`API`, `OutputDir` and `Target` I believe). Each `gen_xxx` package could then add its specific option functions.

**Comment by ottogiron** [comment]
This specific pattern depends on the firm of the option type including the concrete struct that is going to be configured, since it has to have access to public and private properties of that struct.  I tried to think in ways of achieving what you mentioned, but I could not think in practical ways of doing it.

**Comment by raphael** [comment]
Hmm I see, agree that using an interface would not be practical - probably better to repeat the option functions in each package. It seems this PR is ready to merge then? Do you think you could do the same to the other `gen_xxx` packages?

**Comment by ottogiron** [comment]
Sure, I will.

**Comment by raphael** [comment]
Great! Could you also make PRs to backport the changes to the `v1` branch? Thank you!

**Pull request merged**
