### PR TITLE
Add http.Replace() and use it for file servers

### PR DESCRIPTION
**Pull request by tchssk**
This is a fix of #2839.

I'm glad if you release v3.4.3 after merging this. Thank you.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the fix, I will release v3.4.3 once it is merged. I just have one question: would it make sense to refactor `Replace` and `ReplacePrefix` into a single function with an additional argument to differentiate between the two cases or does that end up being too complicated?

**Comment by tchssk** [comment]
I integrated ReplacePrefix into Replace. An additional commit is a fix for `http.FileServer`.

**Comment by raphael** [comment]
This is great thank you!

**Comment by tchssk** [comment]
@raphael 

Would you release v3.4.3? Thank you!

**Comment by raphael** [comment]
Yes I will as soon as https://github.com/goadesign/goa/pull/2858 is merged.

**Comment by raphael** [comment]
I just released v3.4.3 as it's going to take a bit more time to finalize #2858.

**Pull request merged**
