### PR TITLE
Add support for readonly attributes

### PR DESCRIPTION
**Pull request by dikhan**
This pull request adds support for ReadOnly attributes to goa DSL. Payload and MediaType attributes can be set as readonly and the corresponding swagger file generated will render the 'readOnly' as per [swagger 'readOnly' property documentation](https://swagger.io/specification/#fixed-fields-20).

This PR addresses issue #1736

Looking forward to your feedback.

All tests seemed to pass successfully fine with the new change (and additional tests added). An output is attached for the reference:

````
make test
[1529450979] GenClient Suite - 33/33 specs ••••••••••••••••••••••••••••••••• SUCCESS! 10.373164744s PASS
[1529450979] Json Encoding Suite - 3/3 specs ••• SUCCESS! 1.105313ms PASS
[1529450979] Design Suite - 98/98 specs •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 40.898348ms PASS
[1529450979] Test Suite - 1/1 specs • SUCCESS! 797.221µs PASS
[1529450979] GenController Suite - 6/6 specs •••••• SUCCESS! 67.86682ms PASS
[1529450979] GenMain Suite - 6/6 specs •••••• SUCCESS! 1.739633777s PASS
[1529450979] JWT Security Middleware - 25/25 specs ••••••••••••••••••••••••• SUCCESS! 5.999741ms PASS
[1529450979] Codegen Suite - 79/79 specs ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 81.418711ms PASS
[1529450979] Client Suite - 3/3 specs ••• SUCCESS! 1.021765ms PASS
[1529450979] GenJS Suite - 3/3 specs ••• SUCCESS! 18.69709ms PASS
[1529450979] Middleware Suite - 24/24 specs •••••••••••••••••••••••• SUCCESS! 9.606494ms PASS
=== RUN   TestMatchOrigin
--- PASS: TestMatchOrigin (0.00s)
=== RUN   TestMatchOriginRegexp
--- PASS: TestMatchOriginRegexp (0.00s)
PASS
[1529450979] Gzip Suite - 18/18 specs •••••••••••••••••• SUCCESS! 33.652479ms PASS
[1529450979] GenSchema Suite - 4/4 specs •••• SUCCESS! 6.262237ms PASS
[1529450979] Apidsl Suite - 123/123 specs ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 91.274782ms PASS
[1529450979] Goakit Suite - 1/1 specs • SUCCESS! 739.138µs PASS
[1529450979] Meta Suite - 12/12 specs •••••••••••• SUCCESS! 2.121281675s PASS
[1529450979] Logrus Suite - 3/3 specs ••• SUCCESS! 1.316481ms PASS
[1529450979] Goalog15 Suite - 2/2 specs •• SUCCESS! 864.61µs PASS
=== RUN   TestNew
--- PASS: TestNew (0.03s)
=== RUN   TestMiddleware
--- PASS: TestMiddleware (0.01s)
=== RUN   TestNewID
--- PASS: TestNewID (0.00s)
=== RUN   TestNewTraceID
--- PASS: TestNewTraceID (0.00s)
=== RUN   TestPeriodicallyRedialingConn
=== RUN   TestPeriodicallyRedialingConn/dial_fails,_returns_error_immediately
=== RUN   TestPeriodicallyRedialingConn/connection_gets_replaced_by_new_one
=== RUN   TestPeriodicallyRedialingConn/connection_not_replaced_if_dial_errored
--- PASS: TestPeriodicallyRedialingConn (0.01s)
    --- PASS: TestPeriodicallyRedialingConn/dial_fails,_returns_error_immediately (0.00s)
    --- PASS: TestPeriodicallyRedialingConn/connection_gets_replaced_by_new_one (0.00s)
    --- PASS: TestPeriodicallyRedialingConn/connection_not_replaced_if_dial_errored (0.00s)
=== RUN   TestRecordError
--- PASS: TestRecordError (0.00s)
=== RUN   TestRecordResponse
--- PASS: TestRecordResponse (0.00s)
=== RUN   TestRecordRequest
--- PASS: TestRecordRequest (0.00s)
=== RUN   TestNewSubsegment
--- PASS: TestNewSubsegment (0.00s)
=== RUN   TestRace
--- PASS: TestRace (0.00s)
=== RUN   TestTransportExample
--- PASS: TestTransportExample (0.00s)
=== RUN   TestTransportNoSegmentInContext
--- PASS: TestTransportNoSegmentInContext (0.00s)
=== RUN   TestTransport
--- PASS: TestTransport (0.01s)
=== RUN   TestWrapDoer
=== RUN   TestWrapDoer/no_segment_in_context;_success
=== RUN   TestWrapDoer/with_a_segment_in_context_-_successful_request
=== RUN   TestWrapDoer/with_a_segment_in_context_-_failed_request
--- PASS: TestWrapDoer (0.00s)
    --- PASS: TestWrapDoer/no_segment_in_context;_success (0.00s)
    --- PASS: TestWrapDoer/with_a_segment_in_context_-_successful_request (0.00s)
    --- PASS: TestWrapDoer/with_a_segment_in_context_-_failed_request (0.00s)
PASS
[1529450979] GenSwagger Suite - 19/19 specs ••••••••••••••••••• SUCCESS! 730.802591ms PASS
[1529450979] GenApp Suite - 74/74 specs •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 3.848523693s PASS
[1529450979] Goa Suite - 104/104 specs •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••2018/06/20 00:30:26 [INFO] serve file name=public/swagger/swagger.json route=/swagger.json
••••••••••••••••••••••••••••••• SUCCESS! 44.245126ms PASS
[1529450979] Version Suite - 4/4 specs •••• SUCCESS! 1.073188ms PASS
[1529450979] Dslengine Suite - 22/22 specs •••••••••••••••••••••• SUCCESS! 5.315301ms PASS

Ginkgo ran 25 suites in 50.03521s
Test Suite Passed
go test ./_integration_tests
ok      github.com/goadesign/goa/_integration_tests     18.188s

````

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the great PR! I'll fix the build. Something that would be good to change is how the read-only flag is stored. Instead of having a new field on the `AttributeDefinition` struct which is used everywhere it might be better to add a "built-in" metadata. So instead of:

```go
func ReadOnly() {
	if a, ok := attributeDefinition(); ok {
		a.SetReadOnly()
	}
}
```

Do something like:
```
func ReadOnly() {
	if a, ok := attributeDefinition(); ok {
		a.Metadata["swagger:read-only"] = nil
	}
}
```

Then check for this metadata in the OpenAPI generator. This way any agorithm that copies or dups the attribute definition doesn't have to be changed for example. It's also conceptually a good use of metadata because it is not something that affects behavior fundamentally but something that is specific to Swagger generation.

**Comment by raphael** [comment]
Looks great, thank you!

**Comment by raphael** [comment]
Would you mind backporting this PR to the `v1` branch? (simply cherry-pick the merge commit). Thanks!

**Comment by dikhan** [comment]
Thanks @raphael ! 

Created the PR back-porting the changes to v1 branch -> https://github.com/goadesign/goa/pull/1776

Hope that looks good.

Thanks,
Dani

**Pull request merged**
