### PR TITLE
Refactor file server implementation

### PR DESCRIPTION
**Pull request by raphael**
So that it doesn't require introducing a `Replace` function. The new implementation is more robust and properly handles cases where the file path is deep and differs from the mount path.

### CODE REVIEW

**Comment by tchssk** [comment]
This code cannot handle cases where the filename is different between request and file system.
My project contains that cases and v3.19.0 breaks the code.

```go
Files("/index.html", "/www/data/another.html")
```

* Related to https://github.com/goadesign/goa/pull/2856

**Comment by tchssk** [comment]
@raphael

**Comment by raphael** [comment]
Whoops, yes that makes sense, I think we can modify the generated `appendFS` struct to handle this case - let me take a stab at it.

**Comment by raphael** [comment]
Would you be able to test https://github.com/goadesign/goa/pull/3593 to see if its fixes the issue? Thank you!

**Pull request merged**
