### PR TITLE
Backport to v2: Add RFC3339 date format

### PR DESCRIPTION
**Pull request by k-lepa**
Hello,

It's a backport of #1780.

Thanks

### CODE REVIEW

**Comment by k-lepa** [comment]
How do I fix the aliaser's error?

**Comment by raphael** [comment]
The test makes sure that the plugins DSL aliases are up-to-date. There's a blurb at the end of the CI output that explains briefly what to do, in short:

1. Create a 'v2-backport--format-date' branch in the goa.design/plugins repo.
2. Run make in the plugins repo - that will update the "aliases.go" file.
3. Create a PR against the plugins repo

Once the plugins PR is merged I'll re-run the tests above, they should pass and if so I'll merge the PR.

Thanks!

**Comment by k-lepa** [comment]
OK, I'll do it.

**Comment by raphael** [comment]
Thank you!

**Pull request merged**
