### PR TITLE
OpenAPI schema level extensions

### PR DESCRIPTION
**Pull request by townewgokgok**
This PR makes extensions in `Attribute` level (in type definition) merged to `openapi.Schema`.

- `Attribute` level extensions in type definition were not merged to anywhere before this change.
  This can be confirmed by passing the ~1ce4a8579ff2de4ec581e31cbc739b362a31fccd~ ~c89d6d48faf0ef97eab46326348712c933699b21~ 3d439d5037c596e723753bdbc96d3134605ef799 test.
- OpenAPI `Schema` level extensions are [valid](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-objects-9).

Example:

- [Design](https://github.com/sakura-internet/goa/blob/a708fe3fd5f4c2bb4086baf6f969c9034eed99ab/http/codegen/testdata/openapi_v2_dsls.go#L270-L275)
  
  ```go
  var PayloadT = Type("Payload", func() {
      Attribute("string", String, func() {
          Example("")
          Meta("swagger:extension:x-test-schema", "Payload")    // <-
      })
  })
  ```
- [Generated openapi.yaml](https://github.com/sakura-internet/goa/blob/a708fe3fd5f4c2bb4086baf6f969c9034eed99ab/http/codegen/testdata/openapi_v2/TestExtensions/endpoint_file1.golden#L36-L46)
  
  ```yaml
  definitions:
    TestServiceTestEndpointRequestBody:
      title: TestServiceTestEndpointRequestBody
      type: object
      properties:
        string:
          example: ""
          type: string
          x-test-schema: Payload    # <-
      example:
        string: ""
  ```

### CODE REVIEW

**Comment by townewgokgok** [comment]
Related PRs: #2299 #2300 #2301(this)
These conflict, so if you merge them one by one, I will rebase each time.

**Comment by townewgokgok** [comment]
This branch `sakura-internet:openapi_schema_extensions` was rebased onto `v3` after #2299 is merged.

**Comment by townewgokgok** [comment]
This branch `sakura-internet:openapi_schema_extensions` was rebased onto `v3` after #2300 is merged.

**Comment by raphael** [comment]
Thank you!

**Pull request merged**
