### PR TITLE
keep trailing slashes on resource definition

### PR DESCRIPTION
**Pull request by Ragnaroek**
As discussed in Issue #1283

### CODE REVIEW

**Comment by Ragnaroek** [comment]
I don't see how the failing test relate to my change

**Comment by raphael** [comment]
I believe I may have fixed the failing test in master, could you rebase on the latest to see if that fixes it? Thank you!

**Comment by Ragnaroek** [comment]
I messed up the rebase, I will do a new pull request

**Comment by raphael** [comment]
FYI you don't need to create a new PR, you can just force push to the branch once the rebase is clean.

**Comment by Ragnaroek** [comment]
new PR, closing this (it was easier for me)

**Pull request closed without merging**
