### PR TITLE
Fix broken type references in custom package

### PR DESCRIPTION
**Pull request by c-reeder**
Addresses #3198 

- Augmented the description of the `struct:pkg:path` Meta tag to include description of 2 two limitations
- Added validation to check for those two cases
- When that meta tag is set on a user type, internally copy that meta tag down the sub-type tree (for all user types that are fields within it and all user type fields within them)
- Changed one other unrelated Unions line to use existing `AddMeta()` function

### CODE REVIEW

**Comment by ieazie** [comment]
Hi @c-reeder, i wonder if anyone is looking at merging your fix?

**Comment by c-reeder** [comment]
I believe @raphael is going to have a look.

**Comment by raphael** [comment]
Sorry for the delay, the PR looks great. Just one question: would it be possible to add a test? (e.g. to `TestAttributeExprValidate` in `attribute_test.go`). Thank you!

**Comment by raphael** [comment]
@c-reeder friendly reminder, let me know if you are not able to do add a test at this time - would be great to merge this contribution!

**Comment by c-reeder** [comment]
> @c-reeder friendly reminder, let me know if you are not able to do add a test at this time - would be great to merge this contribution!

@raphael so sorry for the delay! This definitely got away from me. Let me have a look back at this and I'll attempt to get a test up for it by the end of the week. 🙂

**Comment by c-reeder** [comment]
@raphael , added a few validation test cases there! Let me know what you think! 🙂

**Comment by raphael** [comment]
Looks great! Thank you.

**Pull request merged**
