### PR TITLE
Fix custom error display that occurred in the decoder 

### PR DESCRIPTION
**Pull request by lev-ok**
This pull request fixes an issue related to displaying a custom error that is returned by the decoder.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the PR, looks good! Would it be possible to add a test that shows what was broken before and what this fixes?

**Comment by raphael** [comment]
@levkoburburas ping, I'd like to merge this PR but would have liked to see an example of "before" and "after" in the form of a test. Do you think that this is something you could provide? thank you!

**Comment by lev-ok** [comment]
> @levkoburburas ping, I'd like to merge this PR but would have liked to see an example of "before" and "after" in the form of a test. Do you think that this is something you could provide? thank you!

Hi @raphael, I apologize for not answering for so long. Sorry, I'm very, very busy right now and don't have enough time to write unit test for this changes. That's OK if you decide to close this PR.

Thanks for this awesome REST API server!

**Comment by raphael** [comment]
I'm going to close this as I don't quite understand the use case that this addresses.

**Pull request closed without merging**
