### PR TITLE
Hijack function to support http.Hijacker in debug middleware

### LINKED ISSUE #2243: v3: Debug middleware for http does not implement Hijacker interface
The default debug middleware used when `--debug` is active does not implement the http.Hijacker interface to work with streaming endpoints using websockets which leads to an `Internal Server Error 500` on those endpoints.

Simple design:
```
package design

import . "goa.design/goa/v3/dsl"

var _ = API("api", func() {
	Server("apisvr", func() {
		Host("default", func() {
			URI("http://0.0.0.0:8000")
			URI("grpc://0.0.0.0:8080")
		})
	})
})

var _ = Service("ws", func() {
	HTTP(func() {
		Path("/")
	})

	Method("Retrieve", func() {
		Payload(func() {
			Field(1, "id", String, "Payload required to avoid issue #2242")
		})

		StreamingResult(String)

		HTTP(func() {
			GET("/{id}")
			Response(StatusOK)
		})
	})
})
```
```
// Retrieve implements Retrieve.
func (s *wssrvc) Retrieve(ctx context.Context, p *ws.RetrievePayload, stream ws.RetrieveServerStream) (err error) {
	s.logger.Println(stream.Send("test"))
	return stream.Close()
}
```
Using with `--debug` gives:
```
[api] 11:27:12 HTTP "Retrieve" mounted on GET /{id}
[api] 11:27:12 HTTP server listening on "0.0.0.0:8000"
[api] 11:27:13  id=1prCzFmU req=GET /test from=127.0.0.1
[api] 11:27:13 websocket: response does not implement http.Hijacker
> [1prCzFmU] GET /test
> [1prCzFmU] Connection: Upgrade
> [1prCzFmU] Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
> [1prCzFmU] Sec-Websocket-Key: XUU617jy94qxuy3TUy0KTA==
> [1prCzFmU] Sec-Websocket-Version: 13
> [1prCzFmU] Upgrade: websocket
< [1prCzFmU] Internal Server Error
< [1prCzFmU] Content-Type: text/plain; charset=utf-8
< [1prCzFmU] Sec-Websocket-Version: 13
< [1prCzFmU] X-Content-Type-Options: nosniff
[1prCzFmU] Internal Server Error
[1prCzFmU] 

[api] 11:27:13  id=1prCzFmU status=500 bytes=22 time=238.644µs
```

### PR DESCRIPTION
**Pull request by cubic3d**
This fixes #2243 by adding a Hijack function, same as in xray to debug middleware to support http.Hijacker interface on streaming endpoints.

### CODE REVIEW

**Comment by cubic3d** [comment]
I can't reproduce linting errors by travis here, same for #2246.

**Comment by raphael** [comment]
Thank you for the PR! I left a comment on #2246 that should help with the linting errors.

**Comment by cubic3d** [comment]
Something is wrong with the examples. Looks like a lorem ipsum generator regenerates an error description.

**Comment by raphael** [comment]
I'll look into why the examples are not always generated with the same output in the mean time re-running the build worked. Thank you!

**Pull request merged**
