### PR TITLE
v3: Fix trailing slash problems

### PR DESCRIPTION
**Pull request by ikawaha**
see https://github.com/goadesign/goa/issues/2557

This patch fixes trailing slash problems to behave as follows.
When a base path is specified and you want to add only / to the end of the base path, you can set the endpoint to `./`.

I hope this fix makes sense.

**Design**

```go
var _ = Service("base_path_no_trailing", func() {
    HTTP(func() { Path("foo") })
    Method("slash_with_base_path_no_trailing", func() {
        HTTP(func() { GET("/") })
    })
    Method("trailing_with_base_path_no_trailing", func() {
        HTTP(func() { POST("/bar/") })
    })
})
var _ = Service("base_path_with_trailing", func() {
    HTTP(func() { Path("foo/") })
    Method("slash_with_base_path_with_trailing", func() {
        HTTP(func() { GET("/") })
    })
})
var _ = Service("no_base_path", func() {
    Method("slash_no_base_path", func() {
        HTTP(func() { GET("/") })
    })
    Method("trailing_no_base_path", func() {
        HTTP(func() { POST("/foo/") })
    })
})
var _ = Service("base_path_no_trailing", func() {
    HTTP(func() { Path("foo") })
    Method("special_case", func() {
        HTTP(func() { GET("./") })
    })
```

**Generated paths**
```
slash_with_base_path_no_trailing: /foo --> ** fixed **
trailing_with_base_path_no_trailing: /foo/bar/
slash_with_base_path_with_trailing: /foo/ --> ** fixed **
slash_no_base_path: /
trailing_no_base_path: /foo/
special_case: /foo/ --> ** special case **
```

### CODE REVIEW

**Review by saniales — APPROVED** [review]

**Comment by cocktailer** [comment]
Please add this patch to v2 also. @ikawaha

**Comment by cocktailer** [comment]
@ikawaha @nitinmohan87 @raphael Can please merge this PR?

**Comment by raphael** [comment]
Thank you for the PR @ikawaha, looks great! just one suggestion: it would be helpful to users to document the behavior above (specifically the "./" special case) in the comment of the `Path` DSL.

**Comment by raphael** [comment]
Great, thank you! Can you please backport to v2 as well? thanks!

**Pull request merged**
