### PR TITLE
Fix code generation of http server when an array of query parameters …

### PR DESCRIPTION
**Pull request by ayanamizuta**
PR of issue #2721

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the report and for the fix, this is great!

The [build is fixed](https://github.com/goadesign/goa/pull/2724) in the latest `v3` head, could you please rebase and update the PR? thank you!

**Comment by ayanamizuta** [comment]
Of course! thx!

**Comment by ayanamizuta** [comment]
Oh, sorry. I'll try to check relevant tests.

**Comment by raphael** [comment]
This is great, thank you!

**Comment by raphael** [comment]
One last request :) Would you mind back-porting the fix to the `v2` branch? Simply cherry-pick the merge commit and create a new PR, thanks!

**Pull request merged**
