### PR TITLE
validate different wildcards only if request method is the same

### PR DESCRIPTION
**Pull request by kovetskiy**
Hi. I noticed that goa design doesn't allow to use different wildcards at the same position for different methods. It's reasonable only if we check wildcard positions in URLs with the same HTTP method. But it's not reasonable to make this check if http methods are different.
My error was:
```
resource "decisions" action "list": route "/api/v1/decisions/:entity/:entityID/" conflicts with route "/api/v1/decisions/:decisionID" of decisions action delete. Make sure wildcards at the same positions have the same name. Conflicting wildcards are "entity" from route GET "/:entity/:entityID/" of resource "decisions" action "list" and "decisionID" from route DELETE "/:decisionID" of resource "decisions" action "delete".
```
So `DELETE "/:decisionID" ` was conflicting with `GET "/:entity/:entityID/"` but there are no really possible conflicts because http methods are different and mux can handle both without any problem.

I made a patch and tested it, works just fine.

### CODE REVIEW

**Comment by kovetskiy** [comment]
https://github.com/goadesign/goa/pull/1583/files?-w with `-w` looks more clear

**Comment by raphael** [comment]
This is great, thank you. Could I convince you to add a test that would have failed before the fix but doesn't with the PR applied? Thank you!

**Comment by kovetskiy** [comment]
@raphael I have added test that fails without my fixes and passes with my fixes.

**Comment by raphael** [comment]
One last thing I promise :) could you backport the fix to the `v1` branch? Simply cherry pick the merge commit and create a new PR targeting the `v1` branch. Thank you!

**Pull request merged**
