### PR TITLE
Issue #555 fix help for -o flag

### PR DESCRIPTION
**Pull request by bits01**
Fix for issue #555

### CODE REVIEW

**Comment by raphael** [comment]
Thank you! doesn't this also change the value that the generators get from an absolute path to `.` ? the generators should be getting an absolute path so if that's the case something should convert the `.` before the value is actually used.

**Comment by bits01** [comment]
It probably does. But does it matter? I can make the change if it matters.

**Comment by bits01** [comment]
Take 2 ... attempt to convert to absolute path. Please review. Thank you.

**Comment by raphael** [comment]
Looks great, thank you!

**Pull request merged**
