### PR TITLE
update logrus import path

### PR DESCRIPTION
**Pull request by hakamata-rui**
Recently Sirpsen/logrus renamed to sirpsen/logrus. 
According to READ.me of sirpsen/logrus, I fixed the import path of logrus.
refs https://github.com/sirupsen/logrus

### CODE REVIEW

**Comment by hakamata-rui** [comment]
Since travis CI seem to be failed due to the timeout, I'd like to close the pull request and reopen this to rebuild.

**Comment by raphael** [comment]
Very helpful, thank you! Could you please backport (cherry pick) this change to the `v1` branch?

**Comment by hakamata-rui** [comment]
Oh, sorry. I've created a pull request about it.

**Comment by raphael** [comment]
Great, thank you!

**Pull request merged**
