### PR TITLE
WIP Split ctx

### PR DESCRIPTION
**Pull request by aslakknutsen**
PR just to keep the conversation open.

NOTE: Tests still not updated.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
@raphael Are these https://github.com/goadesign/goa/blob/master/goagen/gen_app/writers_test.go#L839 intended to be 'copied' from goa-cellar ?

**Comment by raphael** [comment]
@aslakknutsen the idea is to try and keep a common theme throughout the goa-cellar examples and tests - does not have to be an exact copy though. Copy when convenient :) There is an integration test that does a codegen and compiles the goa-cellar example on each goa commit.

**Comment by aslakknutsen** [comment]
@raphael hehe right. I was just looking for the source design to do a regen based on the new changes :)

**Comment by raphael** [comment]
Ah I see, yeah there is no such thing :)

**Comment by raphael** [comment]
I'm closing this for now since it's getting a bit old. Thanks for the work though, should help with v2!

**Comment by aslakknutsen** [comment]
Still want the change, right?

**Comment by raphael** [comment]
Yes absolutely.

**Pull request closed without merging**
