### PR TITLE
Smart package name for gen_controller

### PR DESCRIPTION
**Pull request by tchssk**
This is a backport of #1272 to v1.

### CODE REVIEW

**Comment by raphael** [comment]
I believe the build should be fixed with the latest v1 - could you please rebase with the latest? Thank you!

**Comment by tchssk** [comment]
I'v rebased but same error...

**Comment by raphael** [comment]
The errors in the last build seem like genuine errors (test is asserting `package foo` but generated code has `package controller`).

**Comment by tchssk** [comment]
It seems this error is caused because there is no backport of #1048.

**Comment by raphael** [comment]
Good catch! thank you, #1290 fixes the missing backport.

**Comment by tchssk** [comment]
Thank you. Finally the tests has been passed.

**Comment by raphael** [comment]
Great thank you! One last request :) do you think you could update https://github.com/goadesign/goa.design/blob/master/content/implement/goagen.md to describe the behavior?

**Comment by tchssk** [comment]
Thank you for notifying. I'll update it soon.

**Pull request merged**
