### PR TITLE
Add tests for design.ResultTypeExpr.ComputeViews()

### PR DESCRIPTION
**Pull request by tchssk**
#1423

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the PR! waiting for #1679 to be merged as it changes a little bit how views work in `v2`.

**Comment by nitinmohan87** [comment]
Irrespective of #1679, is this being used anywhere in the codebase?

**Comment by tchssk** [comment]
Oh, it seems not being used yet.

**Comment by raphael** [comment]
Ah maybe it should be removed then, good catch @nitinmohan87 ! Would you mind removing it in #1679? Sorry for the wasted time @tchssk.

**Comment by tchssk** [comment]
No problem!

**Pull request closed without merging**
