### PR TITLE
Fix collecting OpenAPI vendor extensions and tags in root level (#2271)

### PR DESCRIPTION
**Pull request by townewgokgok**
The API level vendor extension was ignored, so when I blame the code, it seemed that this change was the cause.

https://github.com/goadesign/goa/commit/6d9200ca48bab5261f3929cef8f114cf7d55a7ec#diff-6ecbb03fe70b40b52aa6080b1153f04aL53

Similarly for `swagger:tags`

https://github.com/goadesign/goa/commit/6d9200ca48bab5261f3929cef8f114cf7d55a7ec#diff-6ecbb03fe70b40b52aa6080b1153f04aL23

### CODE REVIEW

**Comment by raphael** [comment]
Thank you this is great! do you think you could add a test that would fail without this change?

**Comment by townewgokgok** [comment]
OK, I will try it.

**Comment by townewgokgok** [comment]
Please check the results of #2277 and close it, then review this PR again.

**Comment by townewgokgok** [comment]
Please check the results of #2277 and close it, then review this PR again.

After fixing `swagger:tag:xxx` problem, another problem was found.
Details:
https://github.com/goadesign/goa/pull/2273/files#diff-6ecbb03fe70b40b52aa6080b1153f04aR328-R331
https://github.com/goadesign/goa/pull/2273/files#diff-a9ff15d94de98ce0d197b7bd57e370a8R34

Is the behavior that API level extensions are merged into all tags expected?

**Comment by raphael** [comment]
Thank you for all the work @townewgokgok, this is great. I don't think merging the API level extensions is the right thing to do. Also I believe we should remove the field `Meta` from the `RootExpr` struct (https://github.com/goadesign/goa/blob/40417a02bce8e16ea2c489e5010fa49e131c4e1c/expr/root.go#L35-L37) and remove the line that sets it in the `Meta` function in the `dsl` package (https://github.com/goadesign/goa/blob/40417a02bce8e16ea2c489e5010fa49e131c4e1c/dsl/meta.go#L153-L154) since that's not being used anywhere. Thank you again!

**Comment by townewgokgok** [comment]
Thank you for reviewing.
Do you think it's better to delete these lines together? (The line 331 already exists before sending this PR, and what I did is only adding comments.)
This PR (resolving the problem about API level extensions) will make this behavior reproduced.
https://github.com/goadesign/goa/blob/40417a02bce8e16ea2c489e5010fa49e131c4e1c/http/codegen/openapi/openapi_v2_builder.go#L328-L331

**Comment by raphael** [comment]
@tchssk do you remember why we merge the API level extensions to all other tags?
https://github.com/goadesign/goa/pull/2273#issuecomment-529297937

**Comment by tchssk** [comment]
Sorry, I don't know about it. I was involved swagger extensions in v1 and not v2.

**Comment by raphael** [comment]
@townewgokgok it seems to me that we should be OK removing the merge, thank you!

**Comment by townewgokgok** [comment]
Please review again and merge if there is no problem.

**Comment by raphael** [comment]
Looks great, thank you! Do you think you could back-port these changes to v2? (simply cherry-pick the merge commit into a branch created off of v2 and submit a PR) Thanks!

**Pull request merged**
