### PR TITLE
Inherit API level errors to each service

### PR DESCRIPTION
**Pull request by tchssk**
Related to #2555 #2867 

I think it's useful to be able to inherit API level errors to each service.
This pull request makes it possible.

This is a part of improving Error DSL.
I'll open new ones to improve codegen of http/grpc.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the PR, the idea with API level errors was that they could be referenced but not automatically inherited. So you can define transport level mappings at that level and not have to reproduce them in each service, for example:

```go
var _ = API("my_api", func() {
    Error("Custom")
    HTTP(func() {
        Response("Custom", StatusInternalError)
    })
    GRPC(func() {
        Response("Custom", CodeInvalid)
    })
})

var _ = Service("service", func() {
    Method("meth", func() {
        Error("Custom")
        HTTP(func() {
            GET("/")
            // No need to define response for error "Custom"
        })
        GRPC(func() {
            // No need to define response for error "Custom"
        })
    })
    Method("meth2", func() {
        HTTP(func() {
            GET("/meth2")
            // Does not return error "Custom"
        })
        GRPC(func() {
            // Does not return error "Custom"
        })
    })
})
 
var _ = Service("service2", func() {
    Error("Custom")
     // No need to define response for error "Custom"
     // ....
})
```

I don't think we can change this behavior because it would break existing designs.

**Comment by tchssk** [comment]
Oh I understand it.

> I don't think we can change this behavior because it would break existing designs.

You mean if we use the automatic inheritance, errors will be inherited to also unwanted services, don't you?

It may be possible to realize it by extending `Meta` DSL like below:

```go
var _ = API("my_api", func() {
	Error("Custom", func() {
		Meta("error:inherit:all", true)  // This indicates the error will be inherited to all services.
	})
	HTTP(func() {
		Response("Custom", StatusInternalError)
	})
	GRPC(func() {
		Response("Custom", CodeInvalid)
	})
})

var _ = Service("service", func() {
	Method("meth", func() {
		// No need to define error "Custom"
		HTTP(func() {
			GET("/")
			// No need to define response for error "Custom"
		})
		GRPC(func() {
			// No need to define response for error "Custom"
		})
	})
	Method("meth2", func() {
		HTTP(func() {
			GET("/meth2")
			// Does not return error "Custom"
		})
		GRPC(func() {
			// Does not return error "Custom"
		})
	})
})

var _ = Service("service2", func() {
	// No need to define error "Custom"
	// No need to define response for error "Custom"
	// ....
})
```

or using `Services` DSL:

```go
var _ = API("my_api", func() {
	Error("Custom", func() {
		Services("service1", "service2")  // This indicates the error will be inherited to service1 and service2.
	})
	// ...
})
```

**Comment by raphael** [comment]
Yes that's exactly what I meant. The `Services` DSL is a great idea! It would be consistent with the use in `Server`.

**Comment by tchssk** [comment]
The Services DSL was not bad idea but it has no new feature, just another syntax to behaves like the current API Error.

I'll close this. Thank you for a discussion.

**Pull request closed without merging**
