### PR TITLE
Tag pairs for main

### PR DESCRIPTION
**Pull request by verdverm**
Related to 
tag_pair issue: #592 
tag_pair PR: #593 
example: https://github.com/goadesign/examples/pull/6

This adds two pairs of tags to main for pre/post blocks.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you but as I mentioned in #592 I don't think adding these to `main` adds a lot of value. To me the trade-off is not there.

**Comment by raphael** [comment]
Closing this as I don't believe all the extra comments add value (the main doesn't change save for the mounting of controllers which is easily done manually).

**Comment by verdverm** [comment]
Where do you generally initial databases, read config, and such?

**Comment by raphael** [comment]
What I mean is that the file `main.go` won't change much even if you change the design so it's not worth doing all that work just to get the couple of lines added by the code generator (to mount a new controller - that would be the only change).

Again to be clear: the files `main.go` and all the controller files (files generated at the top level) *are not meant to be regenerated*. The idea is to generate them once to help you get started but then these are *your* code. This is in contrast with e.g. the `app` package that gets entirely re-generated each time.

**Pull request closed without merging**
