### PR TITLE
Add explicit support for x-www-form-urlencoded encoding

### PR DESCRIPTION
**Pull request by raphael**
a.k.a. form encoding

### CODE REVIEW

**Comment by baseman** [comment]
Super thanks! Is there an example of this encoding for the design spec?

**Comment by raphael** [comment]
There's one here: https://github.com/goadesign/examples/blob/master/form_encoding/design/design.go

**Comment by baseman** [comment]
Is there an example of a single endpoint resource action. Thanks for the quick reply

**Comment by raphael** [comment]
Not sure what you mean, the example above only exposes one endpoint.

**Comment by baseman** [comment]
I have two actions under one resource. One accepts application/json, the other x-www-form-urlencoded

**Comment by baseman** [comment]
It kosher I just needed to limit a request action payload to either json or x-www-form-urlencoded but am going to accept both (json or x-www-form-urlencoded) as this is what "Consumes" lets me do similar in the example you provided above

**Comment by raphael** [comment]
Oh I understand now. Yes you need to accept both, goa will take care of picking the right decoder according to the content type header. See http://goa.design/implement/encoding/

**Comment by baseman** [comment]
got it thanks again!

**Comment by KerwinKoo** [comment]
@baseman  @raphael  I'm running into the same issue. Could you show me how to use `x-www-form-urlencoded` , `application/json` and `application/xml` at the same time? I insert 

```
       Consumes("application/x-www-form-urlencoded", func() {
		Package("github.com/goadesign/goa/encoding/form")
	})
	Produces("application/x-www-form-urlencoded", func() {
		Package("github.com/goadesign/goa/encoding/form")
	})
```

into `API` func, it works for `x-www-form-urlencoded` BUT `json` nor `xml`.  

I didn't get the right method from the above example in  http://goa.design/implement/encoding/,  could you show me an example to accept these content type?

Thank you !

**Comment by KerwinKoo** [comment]
Sorry for bothering. I have solved this issue. I found an encoder/decoder example from `goa/encoding/doc.go`.

**Pull request merged**
