### PR TITLE
Remove generation of unnecessary view types.

### PR DESCRIPTION
**Pull request by raphael**

### CODE REVIEW

**Comment by tchssk** [comment]
Something doesn't seem right with this fix. My application doesn't build anymore in v3.18.1.
Maybe We should reconsider #3567 and #3568. @raphael

**Comment by raphael** [comment]
Are you able to put together a repro that causes the issue?

**Comment by tchssk** [comment]
Could you upgrade examples? I triedi it locally and the multipart example failed in lint.

```sh
Making in ./multipart...
go: upgraded goa.design/goa/v3 v3.18.0 => v3.18.1
GENERATING CODE...      
gen/http/cli/resume/cli.go
gen/http/openapi.json  
gen/http/openapi.yaml
gen/http/openapi3.json
gen/http/openapi3.yaml
gen/http/resume/client/cli.go
gen/http/resume/client/client.go
gen/http/resume/client/encode_decode.go
gen/http/resume/client/paths.go
gen/http/resume/client/types.go
gen/http/resume/server/encode_decode.go
gen/http/resume/server/paths.go
gen/http/resume/server/server.go
gen/http/resume/server/types.go
gen/resume/client.go
gen/resume/endpoints.go
gen/resume/service.go
gen/resume/views/view.go

LINTING CODE...
-: # goa.design/examples/multipart/gen/resume/views
gen/resume/views/view.go:36:16: undefined: Experience
gen/resume/views/view.go:38:15: undefined: Education
gen/resume/views/view.go:109:15: undefined: ValidateExperience
gen/resume/views/view.go:116:15: undefined: ValidateEducation (compile)
^ - staticcheck errors!

make[1]: *** [lint] Error 1
make: *** [all] Error 1
```

**Comment by raphael** [comment]
Ohh the release for examples failed and I missed that. Looking into it - thanks for bringing this up!

**Comment by raphael** [comment]
I think this fixes it: https://github.com/goadesign/goa/pull/3569

**Comment by tchssk** [comment]
It's fixed. Thank you for the quick response!

**Pull request merged**
