### PR TITLE
Properly handle params coming in as slices of multiple elements.

### LINKED ISSUE #365: Use multiple parameters with ArrayOf in Params in an Action
Right now, an ArrayOf(String) in a Parameter creates a string slice in generated code, by splitting the first parameter on ",". It seems not  possible to get the other values passed in in the request with multiple Params of the same name.

Since it is easy to split on a comma in client code, given a simple string, Goa would be better off supporting the more complex case of handling multiple parameters with the same name as ArrayOf(String).

### PR DESCRIPTION
**Pull request by raphael**
Fix #365

### CODE REVIEW

**Comment by abourget** [comment]
That's slightly better, I agree.. but it does violate the principle of least surprise.  I can imagine someone starting to use the multi-param feature, and gets bitten in the hoompa-doompa when he discovers that some values were split by `,` .. don't you think ?

Wouldn't we be better to have a different DSL to specify each behavior ?

**Comment by abourget** [comment]
`ArrayOf` and `MultipleKeys` or `MultipleParams` or `FormValues` or `ArrayOfParams` or `ParamsOf` or something ?

**Comment by abourget** [comment]
or add something to `ArrayOf` like: ```ArrayOf(Something, func() {
    MultipleParamsBehavior()
})```

(I know it's not pretty)

**Comment by raphael** [comment]
I understand what you are saying and agree. On the other hand there's also an argument to be made about wanting to keep things simple and avoiding adding yet more DSL (it's always the easy solution). Using commas in query strings doesn't seem like something that would be a common thing to do. I would be more in favor of properly documenting this behavior for now and address the need for not splitting on query string values when a real use case where there's good alternative comes up.

**Pull request merged**
