### PR TITLE
[RFC-WIP] Added new flags to gen_main cmd

### PR DESCRIPTION
**Pull request by hectorj2f**
related to this: https://github.com/goadesign/goa/issues/1040

ping @raphael

### CODE REVIEW

**Comment by raphael** [comment]
Ah you already did the work :( Sorry but I believe these changes would make the tool more confusing to use. It would push for a model where `gen_main` is used every time the design changes when it is not the intent of the tool.

Can you describe exactly how you use it? maybe there's something else that can be done that works for you and stays inline with how the tool was designed. The one use case where I could see some benefit is if you add a new resource and you don't want to have to write the controller struct scaffold by hand. Any other change is trivial to apply. Maybe there could be a `controller`  command that accepts the name of a resource, a path, a package name and produces that scaffold - would that help your use case?

**Comment by hectorj2f** [comment]
@raphael We want to generate the controllers created in `gen_main` and move them into a specific directory and a specific folder. We have our own `main.go` in our project which would like to explicitly call those controllers apart of doing other stuff.

`Maybe there could be a controller command that accepts the name of a resource, a path, a package name and produces that scaffold - would that help your use case?`

With this, you mean to create a new cmd like client, main, ... that does what we need but it's called `controller` ?

**Comment by raphael** [comment]
Yes, something like:
```
goagen controller --res=foo --pkg=main --out=foo.go --design=github.com/foo/bar/design
```
that would generate the controller scaffold `foo.go` where:
* `--res` specifies the name of the resource and is compulsory
* `--pkg` specifies the name of the generated package (defaults to `main`)
* `--out` specifies the name of the relative path to the generated file (defaults to `<name of resource>.go`) 
* `--design` specifies the Go import path of the design package.

**Comment by hectorj2f** [comment]
@raphael I think that would fit into our problem although we might want to also omit the generation of the controller scaffold.

**Comment by raphael** [comment]
The controller scaffold would be the only thing generated in my proposal :) - it's also the only thing that's generated by `gen_main` apart from `main.go`. What is it that you want generated? Maybe just confusing terminology?

**Comment by hectorj2f** [comment]
Okay, that might be the problem but the generator.go of `gen_main` generates two types of files: the mainFile, and the controllers ones. The main.go is the controller scaffold, right ?. I mean I need the other ones.

**Comment by raphael** [comment]
OK we mean the same thing. I call the controller files the controller scaffolds because they are just scaffolding, they don't actually implement the controller logic (that's left to the user).
So it seems that proposal would work for you? One detail that's not clear to me is whether the `controller` generator should override existing files or not. It's scaffold so probably not -on the other hand you call it explicitly... Maybe we do the same as `main` and allow for a `--force` flag.

**Comment by hectorj2f** [comment]
Yeah! I think that having a `--force` flag won't hurt anybody ;). So, I believe I should push a new PR with such a functionality.

**Comment by raphael** [comment]
Sounds great, thank you!

**Comment by hectorj2f** [comment]
I'll close this PR in favour of https://github.com/goadesign/goa/pull/1046. I linked to this one cause the conversation was done here.

**Pull request closed without merging**
