### PR TITLE
added import aliases to external packages in convert.go

### PR DESCRIPTION
**Pull request by ccrossley**
convert.go external imports where being omitted if the package name didn't match the file name.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the great PR, do you think you could write a few tests as well? thanks!

**Comment by raphael** [comment]
Looks great, thanks for all the hard work! Just one question: did you mean to call `SectionCodeFromInputAndMethods` actually `SectionCodeFromImportsAndMethods`?

**Comment by ccrossley** [comment]
Whoops!  Yea I somehow borked the refactor.  I have a commit in the pipe to fix it, hopefully it will show up here soon!

**Comment by raphael** [comment]
Great, thank you!

**Pull request merged**
